### ISSUE TITLE
V2023.02.06 启动后报错

### ISSUE THREAD

**Issue by jinwyp** [Potterli20/trojan-go-fork#50]
1 V2023.02.06 启动后报错

配置

···
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 8443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "bf116f7ed0",
        "6336ded325",
        "2df809ad89",
        "3a9be66bc5",
        "88b70181f7",
        "929a9ebe48",
        "dfd9276c34",
        "a7ea0a99b2",
        "5f8affb3da",
        "ac14c42c1b"
    ],
    "log_level": 1,
    "log_file": "/root/trojan-access.log",
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "/nginxweb/cert/fullchain.cer",
        "key": "/nginxweb/cert/private.key",
        "sni": "xxx1.xxxx.cf",
        "fallback_addr": "127.0.0.1",
        "fallback_port": 80,
        "fingerprint": "chrome"
    }
}

···

错误信息如下：

Feb 11 06:47:55 rsj1 trojan-go[3627582]: goroutine 54 [running]:
Feb 11 06:47:55 rsj1 trojan-go[3627582]: github.com/Potterli20/trojan-go-fork/tunnel/trojan.GetRealIP(0xc00009b6c8?)
Feb 11 06:47:55 rsj1 trojan-go[3627582]:         github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:71 +0x19a
Feb 11 06:47:55 rsj1 trojan-go[3627582]: github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Auth(0xc00025e480)
Feb 11 06:47:55 rsj1 trojan-go[3627582]:         github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:99 +0x257
Feb 11 06:47:55 rsj1 trojan-go[3627582]: github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1({0x1032598?, 0xc000249730})
Feb 11 06:47:55 rsj1 trojan-go[3627582]:         github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:178 +0x1eb
Feb 11 06:47:55 rsj1 trojan-go[3627582]: created by github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop
Feb 11 06:47:55 rsj1 trojan-go[3627582]:         github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:168 +0x105
Feb 11 06:47:55 rsj1 systemd[1]: trojan-go.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

2 https://github.com/Potterli20/trojan-go-fork/releases/download/V2023.01.30/trojan-go-fork-linux-amd64.zip

这个版本V2023.01.30 下载后无法解压 压缩包错误

**Comment by jinwyp** [comment]
我做了一个安装脚本 或拉取最新的代码安装 
https://github.com/jinwyp/one_click_script/blob/master/README2.md

我不可能手动编译， 这个脚本是自动的安装的，都是拉取release

**Comment by jinwyp** [comment]
最新版本的问题运行报错解决了吗?

https://github.com/jinwyp/one_click_script/issues/218

https://github.com/jinwyp/one_click_script/issues/217#issuecomment-1432734892

**Comment by jinwyp** [comment]
> > 最新版本的问题运行报错解决了吗?
> > [jinwyp/one_click_script#218](https://github.com/jinwyp/one_click_script/issues/218)
> > [jinwyp/one_click_script#217 (comment)](https://github.com/jinwyp/one_click_script/issues/217#issuecomment-1432734892)
> 
> 我现在不能给你准确的回答，因为我手动编译并运行很正常，不知道是不是打包问题

有可能是配置文件的问题, 我用的都是兼容trojan-go原版的配置文件.

```
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 8443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "edd7b02f6c",
        "53f168d97e",
        "e1df024cab",
        "1b46d58344",
        "7b5ed503de",
        "68b329da98",
        "bc699f1f13",
        "90505b7a83",
        "4495113538",
        "4490884531"
    ],
    "log_level": 1,
    "log_file": "/root/trojan-access.log",
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "/nginxweb/cert/fullchain.cer",
        "key": "/nginxweb/cert/private.key",
        "sni": "rsj1.tax2.cf",
        "fallback_addr": "127.0.0.1",
        "fallback_port": 80,
        "fingerprint": "chrome"
    },
    "websocket": {
        "enabled": true,
        "path": "/1d1a89dc",
        "host": "rsj1.tax2.cf"
    }
}

```

**Comment by jinwyp** [comment]
> panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn

这报错panic 了啊
panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn

和websocket 相关的问题

**Comment by jinwyp** [comment]
> > > panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn
> > 
> > 
> > 这报错panic 了啊
> > panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn
> > 和websocket 相关的问题
> 
> 这个我修了啊 不行了，我今晚用一下你的脚本

我脚本提供了4种trojan-go  原版trojan  原版trojan-go   还有 fregie/trojan-go 同样的配置只有你这个报错了

**Comment by jinwyp** [comment]
> 

脚本只安装一种trojan-go 根据提示选择就可以安装

**Comment by jinwyp** [comment]
没看懂， 

你用我脚本选2 安装一下 trojan-go 然后选4 就是安装你的trojan-go
 /root/temp 安装完毕就会删除 
程序和配置文件都在/ root/trojan-go 下面 服务也是systemctl status trojan-go.service  不是 trojan.service  
程序名称trojan-go-fork 我重命名为trojan-go


脚本如下
···
wget --no-check-certificate https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x ./trojan_v2ray_install.sh && ./trojan_v2ray_install.sh
···

**Comment by jinwyp** [comment]
可以把你的正常运行的config.json贴一下

我发现报错是使用客户端连接后才报错的， 如果客户端没有连接启动是成功的。
我使用的是v2rayN 5.39 内核是xray 看来应该与客户端有关系

**Comment by jinwyp** [comment]
> > 可以把你的正常运行的config.json贴一下
> > 我发现报错是使用客户端连接后才报错的， 如果客户端没有连接启动是成功的。
> > 我使用的是v2rayN 5.39 内核是xray 看来应该与客户端有关系
> > xray 内核只是实现了trojan协议， 并没有实现trojan-go的更多特性的功能。
> 
> 你那边改一下用curl下载，权限给好，我这边是正常的

和curl没关系 下载的压缩包都已经正常解压了. 你用了v2rayN客户端试了吗? 程序肯定有问题, 换用其他trojan-go 就没问题 配置都一样.

**Comment by jinwyp** [comment]
> 

我脚本可以换任何端口安装啊 不用443 
而且自己改配置也可以换端口运行啊

**Comment by rezaf28** [comment]
https://github.com/Potterli20/trojan-go-fork/commit/331bacb222cc6a396795b2307e88408682c937d1

build and test
Please Check this and reply

**Comment by rezaf28** [comment]
if you have database and only want to Update (Please change YOUR_DATABASE_NAME):
USE YOUR_DATABASE_NAME;
ALTER TABLE `users` ADD `maxip` INT NOT NULL AFTER `upload`;

if you want to Create New Database (Please change YOUR_DATABASE_NAME):
USE YOUR_DATABASE_NAME;
CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password CHAR(56) NOT NULL,
    quota BIGINT NOT NULL DEFAULT 0,
    download BIGINT UNSIGNED NOT NULL DEFAULT 0,
    upload BIGINT UNSIGNED NOT NULL DEFAULT 0,
    maxip int NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX (password)
);

**Comment by jinwyp** [comment]
经测试 [V2023.03.08](https://github.com/Potterli20/trojan-go-fork/releases/tag/V2023.03.08)
已经正常，但还有个小问题 就是配置文件中指定 log 输出文件，log文件 里面没有日志

"log_file": "/root/trojan-access.log",  这个log 还起作用吗？
